# Generated by Django 5.2.1 on 2025-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.BinaryField(max_length=1024),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
