# Generated by Django 5.2.1 on 2025-05-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_rename_user_id_stats_user'),
        ('Login', '0002_alter_users_password_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_minutes', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('workouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.users')),
            ],
        ),
    ]
